### ISSUE TITLE
can't find variable "Q_bin"

### ISSUE THREAD

**Issue by Fried-Fish** [HenryJia/InfoGAN#2]
at Line 161 in InfoGAN.py, "Q_bin" haven't been defined, maybe "self.Q_bin"?
https://github.com/HenryJia/InfoGAN/blob/690136f80db101385907ba72b8fb31078c8c4f2f/InfoGAN.py#L161

**Comment by JJZHK** [comment]
should be self.Q_bin

**Comment by HenryJia** [comment]
Fixed as of 28d21fa51099ff3aa56ca8dcbfef94cfc252c1df
